# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
n=np.random.random((3,3))
n

array([[0.08284511, 0.29205375, 0.79017925],
       [0.15705426, 0.03335289, 0.7610023 ],
       [0.51226259, 0.48433545, 0.98186312]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
import numpy as np
n= np.diag(1+np.arange(4), k = -1)
n

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
import numpy as np
n= np.zeros((8,8))
n[1::2,::2] = 1
n[::2,1::2] = 1
n

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [9]:
n= np.random.random((5,5))
nmax, nmin = n.max(), n.min()
n = (n - nmin)/(nmax - nmin)
n

array([[0.04030543, 0.        , 0.87562908, 0.97067626, 0.77732578],
       [0.46507342, 0.95438343, 0.07626521, 0.83821148, 0.98862598],
       [0.74285537, 0.48483745, 0.54259147, 0.332879  , 0.96597532],
       [0.67692767, 0.89857172, 0.45354927, 1.        , 0.64912887],
       [0.96914405, 0.05560831, 0.65824992, 0.26595873, 0.82824519]])

# 5.  How to find common values between two arrays?

In [13]:
import numpy as np
n=np.array([1,2,3,4,5])
m=np.array([2,3,6,78,9])
print(np.intersect1d(n,m))

[2 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [14]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-01
Today:  2020-08-02
Tomorrow:  2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [16]:
n=np.array([1,2,3,4,5])
m=np.array([2,3,6,78,9])
print((n==m).all())

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [17]:
n=np.random.random(10)
print(n)
n[n.argmax()]=0
n

[0.92768515 0.93287335 0.47514422 0.94705827 0.82064027 0.77467997
 0.4945804  0.18416331 0.67823743 0.40462762]


array([0.92768515, 0.93287335, 0.47514422, 0.        , 0.82064027,
       0.77467997, 0.4945804 , 0.18416331, 0.67823743, 0.40462762])

# 9. How to print all the values of an array?

In [18]:
np.set_printoptions()
n = np.zeros((4, 4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 10.Subtract the mean of each row of a matrix

In [19]:
n=np.random.random((3,3))
print(n)
m=n-n.mean(axis=1)
m

[[0.39395686 0.77087736 0.31883441]
 [0.07372653 0.04210957 0.03395441]
 [0.09473081 0.61329806 0.34864277]]


array([[-0.10059935,  0.72094719, -0.03338947],
       [-0.42082968, -0.0078206 , -0.31826947],
       [-0.3998254 ,  0.56336789, -0.00358111]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [20]:
n = np.ones(10)
m = np.random.randint(0,len(n),20)
np.add.at(n, m, 1)
print(n)

[4. 4. 1. 5. 2. 5. 2. 3. 1. 3.]


# 12.How to get the diagonal of a dot product?

In [21]:
n = np.random.randint(0,10,(4,4))
m= np.random.randint(0,10,(4,4))
np.diag(np.dot(n, m))

array([33, 37, 88, 60])

# 13.How to find the most frequent value in an array?

In [30]:

n=np.array([1,2,3,4,2,11,2,2,2,2,2,1])
print(np.bincount(n).argmax())

2


# 14.How to get the n largest values of an array

In [36]:
n=np.array([1,2,3,4,2,11,2,2,2,2,2,1])
m=1
print (n[np.argpartition(-n,m)[:m]])

[11]


# 15.How to create a record array from a regular array?

In [39]:
n = np.array([("Hi", 2.5, 3),("mani", 3.6, 2)])
m = np.core.records.fromarrays(n.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(m)

[(b'Hi', 2.5, 3) (b'mani', 3.6, 2)]
